version: '2.1'

services:
  radio-stations-server:
    build: .
    container_name: radio-stations-server
    ports:
      - "4123:4123"
    environment:
      - NODE_ENV=production
    restart: always